#!/bin/bash

GREEN="\e[32m"

NORMAL="\033[0m"

 

# Crea nella cartella build/doc la documentazione generata con doxygen

# Il nome viene preso dalla cartella di progetto e la versione da git.

 

mkdir -p ../debug/doc 2> /dev/null

mkdir -p ../release/doc 2> /dev/null

 

cd ..

PROJECT_DIR=${PWD}

NAME=${PROJECT_DIR##*/}

 

echo -e "${GREEN}Generating documentation for ${NAME}${NORMAL}"

 

OUTPUT_DIRECTORY=$(echo $PROJECT_DIR/debug/doc) \

PROJECT_NAME=$(echo "${NAME^}") \

PROJECT_NUMBER=$(git describe --tags --always --abbrev=0) \

doxygen $NAME.doxyfile

 

OUTPUT_DIRECTORY=$(echo $PROJECT_DIR/release/doc) \

PROJECT_NAME=$(echo "${NAME^}") \

PROJECT_NUMBER=$(git describe --tags --always --abbrev=0) \

doxygen $NAME.doxyfile

 

echo -e "${GREEN}Done${NORMAL}"
